### ISSUE TITLE
Ores from Silents Mechanisms is Spawning

### ISSUE THREAD

**Issue by ivardensphere** [GamerHaven/GH-MC#10]
#Configs for specific ores. Set veinCount to zero to disable an ore.
	[world.ores]

		[world.ores.copper]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 8
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 40
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 90

		[world.ores.tin]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 8
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 20
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 80

		[world.ores.silver]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 4
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 0
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 40

		[world.ores.lead]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 4
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 0
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 30

		[world.ores.nickel]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 1
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 6
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 0
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 24

		[world.ores.platinum]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 1
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 5
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 20

		[world.ores.zinc]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 4
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 20
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 60

		[world.ores.bismuth]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 4
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 16
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 64

		[world.ores.bauxite]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 6
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 8
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 15
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 50

		[world.ores.uranium]
			#Number of veins per chunk
			#Range: > 0
			veinCount = 1
			#Size of veins
			#Range: 0 ~ 100
			veinSize = 4
			#Minimum Y-coordinate (base height) of veins
			#Range: 0 ~ 255
			minHeight = 0
			#Maximum Y-coordinate (highest level) of veins
			#Range: 0 ~ 255
			maxHeight = 18

All veinCount should be set to 0 except bismuth as they are handled by AlltheOres.
This is in Silents_mechanisms-common.toml

**Comment by DevilzEye** [comment]
corrected in the configs and uploaded to server

bismuth is at defaults
