### ISSUE TITLE
Copper from Create is spawning

### ISSUE THREAD

**Issue by ivardensphere** [GamerHaven/GH-MC#7]
[worldgen.v2.copper_ore]
#No comment
#Range: > 0
clusterSize = 18
#
#Amount of clusters generated per Chunk.
#  >1 to spawn multiple.
#  <1 to make it a chance.
#  0 to disable.
#Range: 0.0 ~ 512.0
frequency = 2.0

frequency should be set to 0 in create-common.toml

**Comment by DevilzEye** [comment]
set copper and zinc to 0 (alltheores handles zinc as well
