### ISSUE TITLE
Ores from Immersive Engineering are spawning

### ISSUE THREAD

**Issue by ivardensphere** [GamerHaven/GH-MC#8]
#Ore generation config - copper
	[ores.copper]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 72
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#Set this to true to allow retro-generation of copper Ore.
		retrogen_enable = false

	#Ore generation config - bauxite
	[ores.bauxite]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 40
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 85
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 8
		#Set this to true to allow retro-generation of bauxite Ore.
		retrogen_enable = false

	#Ore generation config - lead
	[ores.lead]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 36
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#Set this to true to allow retro-generation of lead Ore.
		retrogen_enable = false

	#Ore generation config - silver
	[ores.silver]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 40
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 4
		#Set this to true to allow retro-generation of silver Ore.
		retrogen_enable = false

	#Ore generation config - nickel
	[ores.nickel]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#Set this to true to allow retro-generation of nickel Ore.
		retrogen_enable = false

	#Ore generation config - uranium
	[ores.uranium]
		#The maximum size of a vein. Set to 0 to disable generation
		#Range: > 0
		vein_size = 0
		#The minimum Y coordinate this ore can spawn at
		#Range: > -2147483648
		min_y = 8
		#The maximum Y coordinate this ore can spawn at
		#Range: > -2147483648
		max_y = 24
		#The average number of veins per chunk
		#Range: > 0
		avg_veins_per_chunk = 2
		#Set this to true to allow retro-generation of uranium Ore.
		retrogen_enable = false

Vein Size should all be set to zero as AllTheOres mod is taking care of these.
This is in file immersiveengineering-server.toml under the the saves/world name/serverconfigs (should be moved to "defaultconfigs").

**Comment by DevilzEye** [comment]
corrected
