### ISSUE TITLE
Ores from Thermal are Spawning

### ISSUE THREAD

**Issue by ivardensphere** [GamerHaven/GH-MC#9]
#Set to FALSE to prevent 'Thermal Series' Copper from generating.
Copper = false
#Set to FALSE to prevent 'Thermal Series' Tin from generating.
Tin = false
#Set to FALSE to prevent 'Thermal Series' Lead from generating.
Lead = false
#Set to FALSE to prevent 'Thermal Series' Silver from generating.
Silver = false
#Set to FALSE to prevent 'Thermal Series' Nickel from generating.
Nickel = false

All these should be set to false.
This is in thermal-server.toml in the saves/world name/serverconfigs folder. (this file should be saved to the "defalutconfigs" folder as well).

**Comment by DevilzEye** [comment]
ah defaultconfigs, it wasnt in there so, ill have to correct that for worldgen. thank you

**Comment by DevilzEye** [comment]
corrected
